function showFatal(message){
  const root=document.getElementById('root');
  const fatal=document.getElementById('fatal');
  if(root)root.classList.add('hidden');
  if(fatal){
    fatal.classList.remove('hidden');
    fatal.innerHTML=`<div class="glass card"><b>UrbanAlert non riesce ad avviarsi.</b><br><span class="muted">${esc(message||'Errore imprevisto. Ricarica la pagina.')}</span></div>`;
  }
}
window.onerror=(message)=>showFatal('Errore JavaScript: '+message);
window.onunhandledrejection=(event)=>showFatal('Errore applicazione: '+((event&&event.reason&&event.reason.message)||'operazione non completata'));

function storageDriver(){
  const memory={};
  const stores=[window.localStorage,window.sessionStorage];
  for(let i=0;i<stores.length;i++){
    try{
      const s=stores[i];
      const key='ua_storage_test';
      s.setItem(key,'1');
      s.removeItem(key);
      return s;
    }catch(e){}
  }
  return {getItem:k=>memory[k]||null,setItem:(k,v)=>{memory[k]=String(v)},removeItem:k=>{delete memory[k]}};
}
const STORE=storageDriver();
const DB={
  get:(k,d)=>{try{const v=STORE.getItem(k);return v?JSON.parse(v):d}catch(e){return d}},
  set:(k,v)=>{try{STORE.setItem(k,JSON.stringify(v))}catch(e){toast('Archivio locale non disponibile','error')}}
};
const DEFAULT_CENTER=[41.9,12.5];
const DEFAULT_ZOOM=6;
const state={user:DB.get('ua_user',null),users:DB.get('ua_users',[]),reports:DB.get('ua_reports',[]),confirmations:DB.get('ua_conf',[]),map:null,mapReady:false,markers:[],userMarker:null,accuracyCircle:null,watchId:null,boundary:null,view:'all'};
const CATS=['buca','rifiuti','illuminazione','segnaletica','acqua','verde pubblico','calamità naturale','altro'];
const EMOJI={buca:'🕳️',rifiuti:'🗑️',illuminazione:'💡',segnaletica:'🚧',acqua:'💧','verde pubblico':'🌳','calamità naturale':'🌪️',altro:'📌'};
const STATUSES=['In attesa','Presa in carico','In lavorazione','Risolta'];

function toast(t,k='ok'){const d=document.createElement('div');d.className='msg '+(k==='error'?'error':'');d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),k==='error'?7200:2600)}
function safe(fn){try{const out=fn();if(out&&typeof out.catch==='function')out.catch(e=>{console.error(e);toast((e&&e.message)||'Operazione non completata','error')});return out}catch(e){console.error(e);toast((e&&e.message)||'Errore imprevisto','error')}}
function persist(){DB.set('ua_user',state.user);DB.set('ua_users',state.users);DB.set('ua_reports',state.reports);DB.set('ua_conf',state.confirmations)}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function uid(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();if(window.crypto&&crypto.getRandomValues){const a=new Uint32Array(4);crypto.getRandomValues(a);return Array.from(a,n=>n.toString(16)).join('-')}return 'ua-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function isInAppBrowser(){return /FBAN|FBAV|Instagram|Line|MicroMessenger|WhatsApp|CriOS.*Mobile\/.*Safari/.test(navigator.userAgent)}

function loginView(){return `<div class='glass login-wrap'><div class='hero'><span class='hero-badge'>🏙️</span><div><h1 class='login-title'>UrbanAlert</h1><div class='login-sub'>Segnala problemi urbani in modo rapido e preciso.</div></div></div><div class='row'><input id='username' placeholder='Nome utente'><select id='role'><option value='cittadino'>cittadino</option><option value='operatore comunale'>operatore comunale</option></select><input id='city' placeholder='Comune di residenza'><input id='opPass' type='password' class='hidden' placeholder='Password operatore'></div><div style='height:12px'></div><button id='loginBtn'>Accedi / Registrati</button></div>`}
function dashboardHtml(){const own=state.reports.filter(r=>r.municipality===state.user.city);const c={attesa:own.filter(r=>r.status==='In attesa').length,work:own.filter(r=>r.status==='In lavorazione').length,res:own.filter(r=>r.status==='Risolta').length,crit:own.filter(r=>r.priority===5).length};return `<div class='dashboard'><div class='stat' data-v='attesa'><small>In attesa</small><h3>${c.attesa}</h3></div><div class='stat' data-v='work'><small>In lavorazione</small><h3>${c.work}</h3></div><div class='stat' data-v='res'><small>Risolte</small><h3>${c.res}</h3></div><div class='stat' data-v='crit'><small>Critiche</small><h3>${c.crit}</h3></div><div class='stat' data-v='rank'><small>Classifica 👍</small><h3>#</h3></div></div><div id='dashList' class='glass card'></div>`}

function render(){try{const root=document.getElementById('root');if(!root)return;if(!state.user){root.innerHTML=loginView();document.getElementById('role').onchange=e=>document.getElementById('opPass').classList.toggle('hidden',e.target.value!=='operatore comunale');document.getElementById('loginBtn').onclick=()=>safe(doLogin);return}
root.innerHTML=`<div class='app-shell'><div class='glass topbar'><div><div class='brand'>UrbanAlert</div><div class='muted'>${esc(state.user.username)} · ${esc(state.user.role)}</div></div><button id='logoutBtn' class='secondary' style='width:auto'>Logout</button></div>${state.user.role==='operatore comunale'?dashboardHtml():''}<div class='glass map-panel'><div class='map-hint'>Tieni premuto sulla mappa per inserire una segnalazione nel punto scelto.</div><div id='map'></div><button id='recenterBtn' class='map-locate-btn' aria-label='La mia posizione'>⌖</button></div><button class='fab' id='createBtn'>Nuova segnalazione</button><div class='glass card'><div class='section-title'><h3>Le mie segnalazioni</h3><small>${myReports().length}</small></div><div class='list'>${myReports().map(reportHtml).join('')||'<div class="item"><b>Nessuna segnalazione.</b><small>Le segnalazioni che invii appariranno qui.</small></div>'}</div></div></div>`;
document.getElementById('logoutBtn').onclick=()=>{state.user=null;persist();render()};document.getElementById('recenterBtn').onclick=()=>safe(()=>centerGPS(true));document.getElementById('createBtn').onclick=()=>safe(createFromCenter);if(state.user.role==='operatore comunale'){bindDashboard();renderDashList()}safe(initMap);bindOpenBtns()}catch(e){console.error('UrbanAlert render error',e);toast('Errore nel caricamento dashboard: '+((e&&e.message)||'riprova a ricaricare'),'error')}}

function doLogin(){try{const username=(document.getElementById('username').value||'').trim();const role=document.getElementById('role').value||'';const city=(document.getElementById('city').value||'').trim();const op=document.getElementById('opPass').value||'';if(!username||!city)return toast('Compila tutti i campi','error');if(role==='operatore comunale'&&op!=='Giorgio24')return toast('Password operatore errata','error');state.user={id:uid(),username,role,city};state.users.push(state.user);persist();render()}catch(e){console.error('UrbanAlert login error',e);toast('Errore durante il login: '+((e&&e.message)||'riprova'),'error')}}
function myReports(){return state.reports.filter(r=>r.authorId===state.user.id)}
function reportHtml(r){return `<div class='item'><b>${EMOJI[r.category]||'📌'} ${esc(r.category)}</b><small>${esc(r.status)} · Priorità ${r.priority||'-'}<br>${esc(r.municipality)} · ${new Date(r.createdAt).toLocaleString()} · 👍 ${r.confirms} · ${esc(r.author)}</small><button data-open='${r.id}'>Apri</button></div>`}
function bindOpenBtns(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openReport(b.dataset.open))}

function bindDashboard(){document.querySelectorAll('.stat').forEach(s=>s.onclick=()=>{state.view=s.dataset.v;renderDashList()})}
function renderDashList(){const box=document.getElementById('dashList');if(!box)return;let arr=state.reports.filter(r=>r.municipality===state.user.city);if(state.view==='attesa')arr=arr.filter(r=>r.status==='In attesa').sort((a,b)=>b.confirms-a.confirms);if(state.view==='work')arr=arr.filter(r=>r.status==='In lavorazione');if(state.view==='res')arr=arr.filter(r=>r.status==='Risolta');if(state.view==='crit')arr=arr.filter(r=>r.priority===5);if(state.view==='rank')arr=arr.sort((a,b)=>b.confirms-a.confirms);box.innerHTML=`<div class='section-title'><h3>${state.view==='rank'?'Classifica problemi più confermati':'Segnalazioni'}</h3><small>${arr.length}</small></div><div class='list'>${arr.map(reportHtml).join('')||'<div class="item"><b>Nessuna segnalazione.</b><small>Non ci sono elementi per questo filtro.</small></div>'}</div>`;bindOpenBtns()}

function showMapError(message){state.mapReady=false;const box=document.getElementById('map');if(box)box.innerHTML=`<div class="map-error"><b>Mappa non disponibile</b><span>${esc(message||'La dashboard resta utilizzabile. Riprova a ricaricare la pagina.')}</span></div>`}
async function initMap(){try{if(state.watchId!==null&&navigator.geolocation){navigator.geolocation.clearWatch(state.watchId);state.watchId=null}if(state.map){state.map.remove()}state.mapReady=false;state.markers=[];state.userMarker=null;state.accuracyCircle=null;state.boundary=null;if(typeof L==='undefined')return showMapError('Leaflet non è stato caricato. Controlla la connessione.');state.map=L.map('map',{zoomControl:false});state.map.setView(DEFAULT_CENTER,DEFAULT_ZOOM);state.mapReady=true;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(state.map);centerGPS(false);if(state.user.role==='operatore comunale')await drawBoundary();renderMarkers();setupLongPress()}catch(e){console.error(e);showMapError((e&&e.message)||'Errore durante il caricamento della mappa')}}
function locationPrecisionMessage(accuracy){if(accuracy>1000)return 'Posizione molto approssimativa';if(accuracy>100)return 'Posizione approssimativa';return 'Posizione aggiornata'}
function updateUserLocation(pos,focus){if(!state.mapReady||!pos||!pos.coords)return;const ll=[pos.coords.latitude,pos.coords.longitude];const accuracy=Math.max(pos.coords.accuracy||0,12);if(!state.userMarker){state.userMarker=L.circleMarker(ll,{radius:9,color:'#0a84ff',fillColor:'#7ec2ff',fillOpacity:1,weight:3}).addTo(state.map)}else{state.userMarker.setLatLng(ll)}if(!state.accuracyCircle){state.accuracyCircle=L.circle(ll,{radius:accuracy,color:'#0a84ff',fillColor:'#7ec2ff',fillOpacity:.12,weight:1}).addTo(state.map)}else{state.accuracyCircle.setLatLng(ll);state.accuracyCircle.setRadius(accuracy)}if(focus)state.map.flyTo(ll,accuracy>1000?12:(accuracy>100?14:16),{duration:.5})}
function geoSupportDebug(){return {isSecureContext:window.isSecureContext===true,userAgent:navigator.userAgent,hasGeolocation:!!navigator.geolocation,protocol:location.protocol,host:location.host}}
function geoErrorCode(error){if(!navigator.geolocation)return 'navigator.geolocation non supportato';if(!error)return 'UNKNOWN';if(error.code===1)return 'PERMISSION_DENIED';if(error.code===2)return 'POSITION_UNAVAILABLE';if(error.code===3)return 'TIMEOUT';return 'UNKNOWN_'+error.code}
async function geolocationPermissionState(){try{if(!navigator.permissions||!navigator.permissions.query)return 'Permissions API non disponibile';const status=await navigator.permissions.query({name:'geolocation'});return status&&status.state?status.state:'stato non disponibile'}catch(e){return 'Permissions API errore: '+((e&&e.message)||'query geolocation fallita')}}
async function showGeoDebugPanel(title,detail,error){if(!isIOS())return;const box=document.querySelector('.map-panel');if(!box)return;const old=document.getElementById('geoDebug');if(old)old.remove();const dbg=geoSupportDebug();const permissionState=await geolocationPermissionState();const userMessage=error&&error.code===1?'Permesso posizione negato. Apri il sito in Safari, vai su aA > Impostazioni sito web > Posizione > Consenti, poi ricarica.':detail;const d=document.createElement('div');d.id='geoDebug';d.className='geo-debug';d.innerHTML=`<b>Posizione non disponibile</b><span>${esc(userMessage)}</span><button type="button" class="geo-details-btn">Dettagli</button><small class="geo-details">window.isSecureContext: ${dbg.isSecureContext}<br>location.protocol: ${esc(dbg.protocol)}<br>navigator.geolocation disponibile: ${dbg.hasGeolocation?'sì':'no'}<br>codice errore geolocation: ${esc(error&&error.code!=null?String(error.code):geoErrorCode(error))}<br>messaggio errore: ${esc((error&&error.message)||'n/d')}<br>permissions.query geolocation: ${esc(permissionState)}<br>userAgent: ${esc(dbg.userAgent)}</small>`;box.appendChild(d);const btn=d.querySelector('.geo-details-btn');const details=d.querySelector('.geo-details');btn.onclick=()=>details.classList.toggle('open')}
function gpsErrorMessage(error){const inApp=isInAppBrowser()?' Apri il link in Safari/Chrome e consenti la posizione.':'';if(!navigator.geolocation)return 'Geolocalizzazione non supportata da questo browser.'+inApp;if(location.protocol!=='https:'&&location.hostname!=='localhost'&&location.hostname!=='127.0.0.1')return 'GPS bloccato: serve HTTPS per usare la posizione precisa.'+inApp;if(error&&error.code===1)return 'PERMISSION_DENIED: permesso posizione negato. In iPhone abilita Posizione per Safari e consenti il sito.'+inApp;if(error&&error.code===2)return 'POSITION_UNAVAILABLE: il dispositivo non riesce a calcolare la posizione. Attiva GPS/Wi‑Fi e riprova.'+inApp;if(error&&error.code===3)return 'TIMEOUT: la posizione non è arrivata entro 15 secondi. Esci all’aperto o riprova.'+inApp;return 'GPS non disponibile. Apri il link in Safari/Chrome e consenti la posizione.'}
async function centerGPS(force){return new Promise(res=>{try{if(!state.mapReady)return res();if(force)toast('Sto cercando la tua posizione...');if(!navigator.geolocation){console.warn('UrbanAlert geolocation unsupported:',geoSupportDebug());toast('Posizione non disponibile','error');return res()}navigator.geolocation.getCurrentPosition(pos=>{try{const old=document.getElementById('geoDebug');if(old)old.remove();console.log('UrbanAlert geolocation success',{lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,debug:geoSupportDebug()});updateUserLocation(pos,true);if(force)toast(locationPrecisionMessage(pos.coords.accuracy||0),pos.coords.accuracy>100?'error':'ok')}catch(e){console.error('UrbanAlert geolocation render error',e);toast('Posizione non disponibile','error')}res()},error=>{console.warn('UrbanAlert geolocation error',{code:geoErrorCode(error),rawCode:error&&error.code,message:error&&error.message,detail:gpsErrorMessage(error),debug:geoSupportDebug()});toast('Posizione non disponibile','error');res()},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}catch(e){console.error('UrbanAlert centerGPS error',e);toast('Posizione non disponibile','error');res()}})}
function startGPSWatch(){if(isIOS()||!navigator.geolocation||state.watchId!==null)return;state.watchId=navigator.geolocation.watchPosition(pos=>updateUserLocation(pos,false),()=>{}, {enableHighAccuracy:true,maximumAge:10000,timeout:15000})}
async function reverseMun(lat,lng){const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}`);const j=await r.json();return (j.address&&j.address.city)||(j.address&&j.address.town)||(j.address&&j.address.village)||'Sconosciuto'}
async function drawBoundary(){try{if(!state.mapReady)return;const q=encodeURIComponent(state.user.city);const r=await fetch(`https://nominatim.openstreetmap.org/search?city=${q}&format=json&polygon_geojson=1&limit=1`);const j=await r.json();if(j[0]&&j[0].geojson){state.boundary=L.geoJSON(j[0].geojson,{style:{color:'#0a84ff',weight:3,fill:false}}).addTo(state.map)}}catch(e){toast('Confine comunale non disponibile','error')}}
function visibleReports(){if(state.user.role==='cittadino')return state.reports.filter(r=>r.status!=='Risolta');return state.reports.filter(r=>r.municipality===state.user.city)}
function renderMarkers(){if(!state.mapReady)return;state.markers.forEach(m=>m.remove());state.markers=[];visibleReports().forEach(r=>{const icon=L.divIcon({className:'',html:`<div style="font-size:24px;line-height:24px;filter:drop-shadow(0 2px 3px rgba(0,0,0,.25));">${EMOJI[r.category]||'📌'}</div>`,iconSize:[24,24],iconAnchor:[12,24],popupAnchor:[0,-20]});const m=L.marker([r.lat,r.lng],{icon}).addTo(state.map).bindPopup(`<div class='chip'>${EMOJI[r.category]||'📌'} ${esc(r.category)}</div><br>${esc(r.status)} · 👍 ${r.confirms}<br><button onclick='openReport("${r.id}")'>Apri</button>`);state.markers.push(m)})}
function setupLongPress(){if(!state.mapReady)return;let t=null,ll=null;const st=e=>{ll=e.latlng;t=setTimeout(()=>openCreate(ll),550)};const clr=()=>{if(t)clearTimeout(t)};state.map.on('mousedown',st);state.map.on('touchstart',st);state.map.on('mouseup',clr);state.map.on('touchend',clr);state.map.on('move',clr)}
function createFromCenter(){if(!state.mapReady)return toast('Mappa non pronta: prova a ricaricare o controlla la connessione','error');openCreate(state.map.getCenter())}

async function openCreate(ll){let mun='Sconosciuto';try{mun=await reverseMun(ll.lat,ll.lng)}catch(e){toast('Comune non rilevato automaticamente','error')}const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class='sheet'><div class='chip'>📍 Posizione acquisita automaticamente</div><h3>Nuova segnalazione</h3><select id='cat'>${CATS.map(c=>`<option value='${c}'>${EMOJI[c]} ${c}</option>`).join('')}</select><textarea id='desc' placeholder='Descrizione opzionale'></textarea><input id='pic' type='file' accept='image/*'><div style='display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px'><button id='send'>Invia segnalazione</button><button id='close' class='secondary'>Chiudi</button></div></div>`;document.body.appendChild(m);m.querySelector('#close').onclick=()=>m.remove();m.querySelector('#send').onclick=async()=>{const f=m.querySelector('#pic').files&&m.querySelector('#pic').files[0];let photo='';if(f)photo=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)});state.reports.push({id:uid(),lat:ll.lat,lng:ll.lng,category:m.querySelector('#cat').value,description:m.querySelector('#desc').value||'',photo,createdAt:new Date().toISOString(),author:state.user.username,authorId:state.user.id,municipality:mun,status:'In attesa',priority:null,confirms:0});persist();m.remove();render();toast('Segnalazione inviata')}}

window.openReport=function(id){safe(()=>{const r=state.reports.find(x=>x.id===id);if(!r)return toast('Segnalazione non trovata','error');const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class='sheet'><div class='chip'>${EMOJI[r.category]||'📌'} ${esc(r.category)}</div><h3>Dettaglio segnalazione</h3><p>${esc(r.description||'Nessuna descrizione')}</p><p><b>Comune:</b> ${esc(r.municipality)}<br><b>Data:</b> ${new Date(r.createdAt).toLocaleString()}<br><b>Stato:</b> ${esc(r.status)}<br><b>Priorità:</b> ${r.priority||'-'}<br><b>Conferme:</b> 👍 ${r.confirms}</p>${r.photo?`<img src='${r.photo}' style='width:100%;border-radius:14px'>`:''}${state.user.role==='cittadino'?`<button id='likeBtn'>👍 Ho notato anche io</button>`:''}${state.user.role==='operatore comunale'?`<select id='st'>${STATUSES.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select><select id='pr'><option value=''>Priorità</option>${[1,2,3,4,5].map(p=>`<option value='${p}' ${p===r.priority?'selected':''}>${p}</option>`).join('')}</select><button id='saveBtn'>Salva</button>`:''}<button id='closeBtn' class='secondary'>Chiudi</button></div>`;document.body.appendChild(m);m.querySelector('#closeBtn').onclick=()=>m.remove();if(m.querySelector('#likeBtn'))m.querySelector('#likeBtn').onclick=()=>{const key=state.user.id+'_'+r.id;if(state.confirmations.indexOf(key)!==-1)return toast('Hai già messo like','error');state.confirmations.push(key);r.confirms++;persist();m.remove();render()};if(m.querySelector('#saveBtn'))m.querySelector('#saveBtn').onclick=()=>{r.status=m.querySelector('#st').value;r.priority=Number(m.querySelector('#pr').value)||null;persist();if(r.status==='Risolta')toast('La tua segnalazione è stata risolta dal comune.');m.remove();render()}})}

render();
